# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCO4LYNLTdOhs9CtmoBsIOJQ5LIY0Ktj
"""

"""
Script principal para resolver el problema de superficies mínimas en S².

Ejecuta:
    python main.py
"""

import numpy as np
import matplotlib.pyplot as plt
from shooting_methods import solve_membrane_bisection, solve_membrane_secant
from visualization import plot_perfil, plot_casquete, plot_energia


# 1. Resolver para un ángulo específico


psi0_deg = 55
psi0 = np.radians(psi0_deg)

print("=" * 60)
print(f"Resolviendo para ψ₀ = {psi0_deg}°")
print("=" * 60)

# Usar bisección (más robusto)
r, psi, dpsi, s_opt, E = solve_membrane_bisection(psi0, N=2000)

print(f"  s = ψ'(0) = {s_opt:.8f}")
print(f"  Energía E(u*) = {E:.8f}")
print(f"  E / (2π) = {E/(2*np.pi):.6f}")
print(f"  Error |ψ(1)-ψ₀| = {abs(psi[-1] - psi0):.2e}")
print("")

# 2. Gráfico del perfil


fig1 = plot_perfil(r, psi, psi0_deg, save_path='imagenes/perfil_psi.png')
plt.show()


# 3. Gráfico 3D del casquete


fig2 = plt.figure(figsize=(8, 6))
ax = fig2.add_subplot(111, projection='3d')
plot_casquete(ax, r, psi, psi0_deg)
plt.tight_layout()
plt.savefig('imagenes/casquete_3d.png', dpi=150, bbox_inches='tight')
plt.show()


# 4. Curva de energía vs ψ₀


print("Calculando energía para varios ángulos...")
angulos = np.linspace(3, 88, 30)
energias = []
s_vals = []

for deg in angulos:
    _, _, _, s, E = solve_membrane_bisection(np.radians(deg), N=1500)
    energias.append(E)
    s_vals.append(s)

fig3 = plot_energia(angulos, np.array(energias), save_path='imagenes/energia_vs_psi0.png')
plt.show()


# 5. Comparación bisección vs secante


print("\nComparación de métodos:")
print("-" * 50)

# Bisección
r_b, psi_b, _, s_b, E_b = solve_membrane_bisection(psi0, N=1500)

# Secante
r_s, psi_s, _, s_s, E_s = solve_membrane_secant(psi0, N=1500)

print(f"  Bisección: s = {s_b:.8f}, E = {E_b:.8f}")
print(f"  Secante:   s = {s_s:.8f}, E = {E_s:.8f}")
print(f"  Diferencia |s_b - s_s| = {abs(s_b - s_s):.2e}")
print(f"  Diferencia |E_b - E_s| = {abs(E_b - E_s):.2e}")
print("=" * 60)