# -*- coding: utf-8 -*-
"""ode_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCO4LYNLTdOhs9CtmoBsIOJQ5LIY0Ktj
"""

"""
Sistema de EDO para el problema de la membrana elástica sobre S^2.

Ecuación:
    ψ'' + ψ'/r = sin(ψ)*cos(ψ)/r²
    ψ(0) = 0, ψ(1) = ψ₀
"""

import numpy as np

def ode_system(r, y):
    """
    Sistema de EDO para el problema de la membrana elástica sobre S^2.

    y = (ψ, ψ')

    Parámetros
    ----------
    r : float
        coordenada radial
    y : array [ψ, ψ']
        estado actual

    Retorna
    -------
    dy : array [ψ', ψ'']
        derivadas
    """
    psi, dpsi = y

    # Evitar singularidad en r=0 (L'Hôpital)
    if r < 1e-10:
        return [dpsi, 0.0]

    # Ecuación de Euler-Lagrange
    return [dpsi, np.sin(psi) * np.cos(psi) / r**2 - dpsi / r]