# -*- coding: utf-8 -*-
"""shooting methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCO4LYNLTdOhs9CtmoBsIOJQ5LIY0Ktj
"""

"""
Métodos de disparo (shooting) para resolver el PVF:
    ψ(0) = 0, ψ(1) = ψ₀

Métodos implementados:
- Bisección
- Secante
"""

import numpy as np
from scipy.integrate import solve_ivp
from ode_system import ode_system

def solve_membrane_bisection(psi0, N=2000, eps=1e-3):
    """
    Resuelve el PVF usando disparo + bisección.

    Parámetros
    ----------
    psi0 : float
        colatitud de frontera (radianes)
    N : int
        número de nodos de integración
    eps : float
        inicio de integración (evita r=0)

    Retorna
    -------
    r_vals : array
        nodos radiales (incluye r=0)
    psi_v : array
        valores de ψ(r)
    dpsi_v : array
        valores de ψ'(r)
    s_opt : float
        parámetro de disparo óptimo ψ'(0)
    energy : float
        energía del minimizante E(u*)
    """

    def shoot(s):
        """Integra la EDO y devuelve ψ(1; s)."""
        sol = solve_ivp(
            ode_system,
            (eps, 1.0),
            [s * eps, s],
            method='RK45',
            t_eval=np.linspace(eps, 1.0, N),
            rtol=1e-11, atol=1e-13,
        )
        return sol.y[0, -1]

    # ── 1. Encontrar bracket [s_lo, s_hi] ──
    s_lo, s_hi = 0.0, 5.0
    for _ in range(20):
        if shoot(s_hi) >= psi0:
            break
        s_hi *= 2.0

    # ── 2. Bisección ──
    for _ in range(80):
        s_mid = (s_lo + s_hi) / 2.0
        if shoot(s_mid) < psi0:
            s_lo = s_mid
        else:
            s_hi = s_mid
    s_opt = (s_lo + s_hi) / 2.0

    # ── 3. Integración final ──
    sol = solve_ivp(
        ode_system,
        (eps, 1.0),
        [s_opt * eps, s_opt],
        method='RK45',
        t_eval=np.linspace(eps, 1.0, N),
        rtol=1e-11, atol=1e-13,
    )

    # ── 4. Post-procesamiento ──
    r_vals = np.concatenate([[0.0], sol.t])
    psi_v = np.concatenate([[0.0], sol.y[0]])
    dpsi_v = np.concatenate([[s_opt], sol.y[1]])

    # Energía: E = π * ∫₀¹ [ψ'² r + sin²(ψ)/r] dr
    r_ = sol.t
    intgd = sol.y[1]**2 * r_ + np.sin(sol.y[0])**2 / r_
    energy = np.pi * np.trapezoid(intgd, r_)

    return r_vals, psi_v, dpsi_v, s_opt, energy


def solve_membrane_secant(psi0, N=2000, eps=1e-3,
                          tol_phi=1e-12, tol_s=1e-12, max_iter=40):
    """
    Resuelve el PVF usando disparo + secante.
    """

    def shoot(s):
        sol = solve_ivp(
            ode_system,
            (eps, 1.0),
            [s * eps, s],
            method='RK45',
            t_eval=np.linspace(eps, 1.0, N),
            rtol=1e-11, atol=1e-13,
        )
        return sol.y[0, -1]

    def phi(s):
        return shoot(s) - psi0

    # Semillas iniciales
    s0, f0 = 0.0, phi(0.0)
    s1, f1 = 5.0, phi(5.0)

    # Asegurar bracket
    for _ in range(25):
        if f1 > 0:
            break
        s1 *= 2.0
        f1 = phi(s1)

    # Secante
    s_opt = s1
    for k in range(max_iter):
        denom = f1 - f0
        if abs(denom) < 1e-15:
            break

        s2 = s1 - f1 * (s1 - s0) / denom
        if s2 <= 0:
            s2 = 0.5 * (s0 + s1)

        f2 = phi(s2)
        s_opt = s2

        if abs(f2) < tol_phi or abs(s2 - s1) < tol_s * max(1.0, abs(s2)):
            break

        s0, f0 = s1, f1
        s1, f1 = s2, f2

    # Integración final
    sol = solve_ivp(
        ode_system,
        (eps, 1.0),
        [s_opt * eps, s_opt],
        method='RK45',
        t_eval=np.linspace(eps, 1.0, N),
        rtol=1e-11, atol=1e-13,
    )

    r_vals = np.concatenate([[0.0], sol.t])
    psi_v = np.concatenate([[0.0], sol.y[0]])
    dpsi_v = np.concatenate([[s_opt], sol.y[1]])

    r_ = sol.t
    intgd = sol.y[1]**2 * r_ + np.sin(sol.y[0])**2 / r_
    energy = np.pi * np.trapezoid(intgd, r_)

    return r_vals, psi_v, dpsi_v, s_opt, energy