# -*- coding: utf-8 -*-
"""Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCO4LYNLTdOhs9CtmoBsIOJQ5LIY0Ktj
"""

"""
Funciones para visualizar los resultados del problema de superficies mínimas.
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


def plot_perfil(r, psi, psi0_deg, save_path=None):
    """
    Genera el gráfico del perfil ψ(r).

    Parámetros
    ----------
    r : array
        nodos radiales
    psi : array
        valores de ψ(r)
    psi0_deg : float
        ángulo de frontera en grados
    save_path : str, opcional
        ruta para guardar la figura
    """
    fig, ax = plt.subplots(figsize=(8, 5))

    ax.plot(r, np.degrees(psi), lw=2.5, color='steelblue',
            label=r'Solución numérica $\psi(r)$')
    ax.plot([0, 1], [0, psi0_deg], 'k--', lw=1.5, alpha=0.5,
            label=r'Perfil lineal $\psi_0 r$')
    ax.axhline(psi0_deg, color='goldenrod', ls=':', lw=1.2, alpha=0.7,
               label=f'$\psi_0 = {psi0_deg:.0f}°$')

    # Relleno para mostrar la diferencia
    ax.fill_between(r, np.degrees(psi), r * psi0_deg,
                    alpha=0.15, color='steelblue',
                    label='Efecto de curvatura de $S^2$')

    ax.set_xlabel(r'$r$', fontsize=12)
    ax.set_ylabel(r'$\psi(r)$ (grados)', fontsize=12)
    ax.set_title(f'Perfil armónico para $\psi_0 = {psi0_deg:.0f}°$', fontsize=14)
    ax.legend(loc='upper left', fontsize=10)
    ax.grid(True, alpha=0.3)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, max(psi0_deg + 5, 10))

    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')

    return fig


def plot_casquete(ax, r, psi, psi0_deg, title=None):
    """
    Dibuja el casquete esférico en 3D.

    Parámetros
    ----------
    ax : Axes3D
        eje 3D de matplotlib
    r : array
        nodos radiales
    psi : array
        valores de ψ(r)
    psi0_deg : float
        ángulo de frontera en grados
    title : str, opcional
        título del gráfico
    """
    theta = np.linspace(0, 2 * np.pi, 90)
    R_g, T_g = np.meshgrid(r, theta)
    Psi_g = np.interp(R_g, r, psi)

    X = np.sin(Psi_g) * np.cos(T_g)
    Y = np.sin(Psi_g) * np.sin(T_g)
    Z = np.cos(Psi_g)

    norm = plt.Normalize(0, np.pi / 2)
    ax.plot_surface(
        X, Y, Z,
        facecolors=plt.cm.cool(norm(Psi_g)),
        alpha=0.88, linewidth=0.1, rstride=2, cstride=2
    )

    # Borde del casquete (imagen de ∂𝔻)
    th = np.linspace(0, 2*np.pi, 200)
    psi_b = np.radians(psi0_deg)
    ax.plot(
        np.sin(psi_b) * np.cos(th),
        np.sin(psi_b) * np.sin(th),
        np.cos(psi_b) * np.ones_like(th),
        color='goldenrod', lw=2.5, zorder=5,
        label=f'Borde $\psi_0 = {psi0_deg:.0f}°$'
    )

    # Esfera fantasma
    phi_g = np.linspace(0, np.pi, 20)
    for th_ in np.linspace(0, 2*np.pi, 8, endpoint=False):
        ax.plot(
            np.sin(phi_g) * np.cos(th_),
            np.sin(phi_g) * np.sin(th_),
            np.cos(phi_g),
            color='slategray', lw=0.7, alpha=0.3
        )

    for lat_ in np.linspace(0.2, np.pi*0.95, 5):
        th_ = np.linspace(0, 2*np.pi, 50)
        ax.plot(
            np.sin(lat_) * np.cos(th_),
            np.sin(lat_) * np.sin(th_),
            np.cos(lat_) * np.ones_like(th_),
            color='slategray', lw=0.7, alpha=0.3
        )

    ax.set_xlabel('x', fontsize=10)
    ax.set_ylabel('y', fontsize=10)
    ax.set_zlabel('z', fontsize=10)
    ax.set_title(title or f'Casquete esférico, $\psi_0 = {psi0_deg:.0f}°$', fontsize=12)
    ax.set_xlim(-1, 1)
    ax.set_ylim(-1, 1)
    ax.set_zlim(-0.1, 1.05)

    # Ajustar ángulo de vista
    ax.view_init(elev=25, azim=40)


def plot_energia(angulos, energias, save_path=None):
    """
    Genera el gráfico de energía vs ψ₀.

    Parámetros
    ----------
    angulos : array
        ángulos en grados
    energias : array
        energías correspondientes
    save_path : str, opcional
        ruta para guardar la figura
    """
    fig, ax = plt.subplots(figsize=(8, 5))

    ax.plot(angulos, energias, 'o-', color='steelblue', lw=2, ms=5,
            label='$E(u^*)$ (numérico)')

    # Área del casquete (referencia teórica)
    area = 2*np.pi * (1 - np.cos(np.radians(angulos)))
    ax.plot(angulos, area, 's--', color='seagreen', lw=1.5, ms=4, alpha=0.7,
            label='Área del casquete $2\pi(1-\cos\psi_0)$')

    ax.axhline(2*np.pi, color='red', ls=':', lw=1.5, alpha=0.7,
               label='$2\pi$ (hemisferio)')

    ax.set_xlabel(r'$\psi_0$ (grados)', fontsize=12)
    ax.set_ylabel('Energía $E(u^*)$', fontsize=12)
    ax.set_title('Energía del minimizante vs ángulo de frontera', fontsize=14)
    ax.legend(loc='upper left', fontsize=10)
    ax.grid(True, alpha=0.3)

    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')

    return fig